In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("trace_data.csv")

In [3]:
df = df.loc[:,[x for x in df.columns if x != "Unnamed: 0"]]
df.sort_values(['rawTime', 'mac'], inplace=True)
df.head()

,time,posX,posY,orientation,mac,signal,channel,rawTime,angle
0,2006-02-10 23:31:58,0,0,0.0,00:14:bf:b1:97:8a,-38,2437000000,1139643118358,0
1,2006-02-10 23:31:58,0,0,0.0,00:14:bf:b1:97:90,-56,2427000000,1139643118358,0
2,2006-02-10 23:31:58,0,0,0.0,00:0f:a3:39:e1:c0,-53,2462000000,1139643118358,0
3,2006-02-10 23:31:58,0,0,0.0,00:14:bf:b1:97:8d,-65,2442000000,1139643118358,0
4,2006-02-10 23:31:58,0,0,0.0,00:14:bf:b1:97:81,-65,2422000000,1139643118358,0

In [15]:
macs = ["00:0f:a3:39:e1:c0", "00:0f:a3:39:dd:cd"]
df[df.mac.isin(macs)].head()

,time,posX,posY,orientation,mac,signal,channel,rawTime,angle
6,2006-02-10 23:31:58,0,0,0.0,00:0f:a3:39:dd:cd,-75,2412000000,1139643118358,0
2,2006-02-10 23:31:58,0,0,0.0,00:0f:a3:39:e1:c0,-53,2462000000,1139643118358,0
16,2006-02-10 23:31:58,0,0,0.0,00:0f:a3:39:dd:cd,-73,2412000000,1139643118744,0
10,2006-02-10 23:31:58,0,0,0.0,00:0f:a3:39:e1:c0,-54,2462000000,1139643118744,0
26,2006-02-10 23:31:59,0,0,0.0,00:0f:a3:39:dd:cd,-65,2412000000,1139643119002,0

In [16]:
df.sort_values(['mac', 'rawTime', 'channel'], inplace=True)
df.head(100)

,time,posX,posY,orientation,mac,signal,channel,rawTime,angle
592,2006-02-10 23:32:16,0,0,0.0,00:04:0e:5c:23:fc,-93,2472000000,1139643136952,0
826,2006-02-10 23:32:25,0,0,0.0,00:04:0e:5c:23:fc,-93,2472000000,1139643145108,0
825,2006-02-10 23:32:25,0,0,0.0,00:04:0e:5c:23:fc,-93,2472000000,1139643145108,0
824,2006-02-10 23:32:25,0,0,0.0,00:04:0e:5c:23:fc,-93,2472000000,1139643145108,0
823,2006-02-10 23:32:25,0,0,0.0,00:04:0e:5c:23:fc,-93,2472000000,1139643145108,0
1668,2006-02-10 23:34:25,0,0,90.3,00:04:0e:5c:23:fc,-92,2472000000,1139643265396,90
1672,2006-02-10 23:34:25,0,0,90.3,00:04:0e:5c:23:fc,-93,2472000000,1139643265396,90
1671,2006-02-10 23:34:25,0,0,90.3,00:04:0e:5c:23:fc,-93,2472000000,1139643265396,90
1670,2006-02-10 23:34:25,0,0,90.3,00:04:0e:5c:23:fc,-93,2472000000,1139643265396,90
1669,2006-02-10 23:34:25,0,0,90.3,00:04:0e:5c:23:fc,-92,2472000000,1139643265396,90
1673,2006-02-10 23:34:25,0,0,90.3,00:04:0e:5c:23:fc,-93,2472000000,1139643265396,90
1729,2006-02-10 23:34:27,0,0,90.3,00:04:0e:5c:23:fc,-92,2472000000,1139643267172,90
1728,2006-02-10 23:34:27,0,0,90.3,00:04:0e:5c:23:fc,-91,2472000000,1139643267172,90
1754,2006-02-10 23:34:27,0,0,90.3,00:04:0e:5c:23:fc,-92,2472000000,1139643267928,90
1753,2006-02-10 23:34:27,0,0,90.3,00:04:0e:5c:23:fc,-91,2472000000,1139643267928,90
1752,2006-02-10 23:34:27,0,0,90.3,00:04:0e:5c:23:fc,-91,2472000000,1139643267928,90
1774,2006-02-10 23:34:28,0,0,90.3,00:04:0e:5c:23:fc,-93,2472000000,1139643268432,90
1798,2006-02-10 23:34:29,0,0,90.3,00:04:0e:5c:23:fc,-92,2472000000,1139643269188,90
1797,2006-02-10 23:34:29,0,0,90.3,00:04:0e:5c:23:fc,-91,2472000000,1139643269188,90
1808,2006-02-10 23:34:29,0,0,90.3,00:04:0e:5c:23:fc,-91,2472000000,1139643269440,90
1812,2006-02-10 23:34:29,0,0,90.3,00:04:0e:5c:23:fc,-92,2472000000,1139643269440,90
1811,2006-02-10 23:34:29,0,0,90.3,00:04:0e:5c:23:fc,-92,2472000000,1139643269440,90
1810,2006-02-10 23:34:29,0,0,90.3,00:04:0e:5c:23:fc,-91,2472000000,1139643269440,90
1809,2006-02-10 23:34:29,0,0,90.3,00:04:0e:5c:23:fc,-91,2472000000,1139643269440,90
1819,2006-02-10 23:34:29,0,0,90.3,00:04:0e:5c:23:fc,-91,2472000000,1139643269692,90
1821,2006-02-10 23:34:29,0,0,90.3,00:04:0e:5c:23:fc,-93,2472000000,1139643269692,90
1828,2006-02-10 23:34:29,0,0,90.3,00:04:0e:5c:23:fc,-91,2472000000,1139643269944,90
1829,2006-02-10 23:34:29,0,0,90.3,00:04:0e:5c:23:fc,-92,2472000000,1139643269944,90
1839,2006-02-10 23:34:30,0,0,90.3,00:04:0e:5c:23:fc,-92,2472000000,1139643270196,90
1838,2006-02-10 23:34:30,0,0,90.3,00:04:0e:5c:23:fc,-91,2472000000,1139643270196,90
...,...,...,...,...,...,...,...,...,...
2498,2006-02-10 23:34:49,0,0,90.3,00:04:0e:5c:23:fc,-91,2472000000,1139643289373,90
2497,2006-02-10 23:34:49,0,0,90.3,00:04:0e:5c:23:fc,-91,2472000000,1139643289373,90
2496,2006-02-10 23:34:49,0,0,90.3,00:04:0e:5c:23:fc,-91,2472000000,1139643289373,90
2495,2006-02-10 23:34:49,0,0,90.3,00:04:0e:5c:23:fc,-91,2472000000,1139643289373,90
2509,2006-02-10 23:34:49,0,0,90.3,00:04:0e:5c:23:fc,-91,2472000000,1139643289625,90
2511,2006-02-10 23:34:49,0,0,90.3,00:04:0e:5c:23:fc,-92,2472000000,1139643289625,90
2539,2006-02-10 23:34:50,0,0,90.3,00:04:0e:5c:23:fc,-93,2472000000,1139643290389,90
2538,2006-02-10 23:34:50,0,0,90.3,00:04:0e:5c:23:fc,-92,2472000000,1139643290389,90
2537,2006-02-10 23:34:50,0,0,90.3,00:04:0e:5c:23:fc,-92,2472000000,1139643290389,90
2536,2006-02-10 23:34:50,0,0,90.3,00:04:0e:5c:23:fc,-91,2472000000,1139643290389,90
2535,2006-02-10 23:34:50,0,0,90.3,00:04:0e:5c:23:fc,-91,2472000000,1139643290389,90
2559,2006-02-10 23:34:50,0,0,90.3,00:04:0e:5c:23:fc,-91,2472000000,1139643290893,90
2558,2006-02-10 23:34:50,0,0,90.3,00:04:0e:5c:23:fc,-91,2472000000,1139643290893,90
2560,2006-02-10 23:34:50,0,0,90.3,00:04:0e:5c:23:fc,-92,2472000000,1139643290893,90
2580,2006-02-10 23:34:51,0,0,90.3,00:04:0e:5c:23:fc,-92,2472000000,1139643291397,90
2588,2006-02-10 23:34:51,0,0,90.3,00:04:0e:5c:23:fc,-91,2472000000,1139643291649,90
2604,2006-02-10 23:34:52,0,0,90.3,00:04:0e:5c:23:fc,-91,2472000000,1139643292153,90
2792,2006-02-10 23:35:32,0,0,135.9,00:04:0e:5c:23:fc,-93,2472000000,1139643332604,135
2791,2006-02-10 23:35:32,0,0,135.9,00:04:0e:5c:23:fc,-92,2472000000,1139643332604,135
2949,2006-02-10 23:35:37,0,0,135.9,00:04:0e:5c:23:fc,-93,2472000000,1139643337400,135
3085,2006-02-10 23:35:41,0,0,135.9,00:04:0e:5c:23:fc,-93,2472000000,1139643341432,135
3194,2006-02-10 23:35:44,0,0,135.9,00:04:0e:5c:23:fc,-92,2472000000,1139643344709,135
3195,2006-02-10 23:35:44,0,0,135.9,00:04:0e:5c:23:fc,-93,2472000000,1139643344709,135
3197,2006-02-10 23:35:44,0,0,135.9,00:04:0e:5c:23:fc,-94,2472000000,1139643344709,135
3196,2006-02-10 23:35:44,0,0,135.9,00:04:0e:5c:23:fc,-93,2472000000,1139643344709,135
3192,2006-02-10 23:35:44,0,0,135.9,00:04:0e:5c:23:fc,-92,2472000000,1139643344709,135
3191,2006-02-10 23:35:44,0,0,135.9,00:04:0e:5c:23:fc,-92,2472000000,1139643344709,135
3355,2006-02-10 23:35:49,0,0,135.9,00:04:0e:5c:23:fc,-94,2472000000,1139643349257,135
3354,2006-02-10 23:35:49,0,0,135.9,00:04:0e:5c:23:fc,-93,2472000000,1139643349257,135
3353,2006-02-10 23:35:49,0,0,135.9,00:04:0e:5c:23:fc,-93,2472000000,1139643349257,135